### ISSUE TITLE
Add System PVs

### ISSUE THREAD

**Issue by fgretief** [yamcs/opi.js#11]
Some displays show the time in Yamcs Studio using the `sys://time` PV. But that value is not available in the web interface.

Would it be possible to add at least `sys://time`?

The other fields in the group of [system PVs](https://docs.yamcs.org/yamcs-studio/pv/sys/) does not make much sense, but returning at least fixed/dummy values will keep displays more compatible with Yamcs Studio.

**Comment by fqqb** [comment]
Latest release (for inclusion in next Yamcs release) will recognize ``sys://time``.

For the other ones, I prefer to keep them as-is (disconnected). The one that provides access to system properties could potentially make use of a browser's Local Storage, but I would need an actual use case, before implementing anything like that.
