### ISSUE TITLE
Transparency property of XY Graph not working

### ISSUE THREAD

**Issue by guidoSNT** [yamcs/opi.js#12]
Hi, I've been using the XY Graph in Yamcs Studio to do some maps by using an image and the XY Graph with the "Transparent" property in the Display section. When I tried to port the project to yamcs web the background of the graph keeps the color despite the transparency.

To emulate: 

1. Create a project with a black backgroud.
2.  Add an XY graph and set the Transparentl property to "Yes".
3.  Load the Opi file to the quickstart example and compare the result to the Display runner.

It should look like this in Yamcs Studio:

![Screenshot from 2024-05-21 15-09-08](https://github.com/yamcs/opi.js/assets/146991359/4b0ac71a-41cf-42ef-a098-1733b4bcaf13)

In the web it looks like this:
![Screenshot from 2024-05-21 15-11-06](https://github.com/yamcs/opi.js/assets/146991359/5c404c36-ce23-4c2c-938e-d10671fee602)

**Comment by guidoSNT** [comment]
I forgot to mention in the issue that maybe implementing some kind of basic mapping tool, or a way to set an image as a background for XY graphs would be very useful, but I guess it is a feature that should be added first to Yamcs Studio.

**Comment by fqqb** [comment]
Latest release (for inclusion in next Yamcs release) will improve XY Graph transparency (to include both plot area and legend backgrounds).

For the image background, yes, that would be a studio request. But even then, with transparency working, it seems to me you could just place an Image widget under the XY Graph.
