### ISSUE TITLE
Refreshing TabbedContainer widget in Yamcs web

### ISSUE THREAD

**Issue by tacooper** [yamcs/opi.js#3]
I've noticed that the TabbedContainer widget does not draw properly when uploaded to Yamcs web. I tested using Firefox and Chrome in Ubuntu 18.04. Here are my detailed steps:

1. In Yamcs Studio, I created a TabbedContainer widget with several tabs, each containing an XY Graph widget.
2. When testing with the Display Runner, each tab can be clicked and its associated XY Graph shown as expected.
3. On the Yamcs server's web page, I uploaded the OPI file to Telemetry > Displays, then clicked to open that display.
4. When clicking each tab, the associated XY Graph is shown on top of other tabs' graphs, as if the drawing is not cleared during each tab switch.

Is this a known issue with TabbedContainer and/or XY Graph widgets that needs to be tracked/fixed?
Are there any workarounds I can try to refresh the drawing in the Yamcs web display?

**Comment by tacooper** [comment]
Thank you for redirecting this issue to its appropriate home project and for taking a quick attempt at it.

**Comment by fqqb** [comment]
Fixed on master. Shall be in a next release of Yamcs.
