### ISSUE TITLE
Macros are not passed in OpenOPI Actions

### ISSUE THREAD

**Issue by aerospacesoftware** [yamcs/opi.js#7]
Macros do not appear to be passed from an action button to a child OPI

To reproduce:
Create an Action button
Set Action to Open OPI
Add a macro called macro_name give it a value
Create a text update widget in the OPI to be opened and set the Text field to ${macro_name}

Run in Yamcs builder; the text update widget will show macro value
Run opi.js from yamcs/telemetry/displays and the text update widget will show '${macro_value}'

**Comment by fqqb** [comment]
Shall be included in next release of Yamcs.
The function to pass parent macros is not yet implemented, only the ones specified in the action itself.
