### ISSUE TITLE
Macros not expanded in Commands name or arguments

### ISSUE THREAD

**Issue by aerospacesoftware** [yamcs/opi.js#8]
In yamcs-studio

Create two macros, macro_command =myCommand and macro_argument=myArgument

Create an action button

Assign Run Command Action 
Make the command name ${macro_command}
Add an argument with name arg1 and value ${macro_argument}

Open dashboard and click button.  The command name and the argument will be expanded so the action will be 'myCommand myArgument'

Open same dashboard from browser (in opi.js).  Action will be '${macro_command} ${macro_argument}', i.e. not expanded

**Comment by aerospacesoftware** [comment]
Proposed patch




diff --git a/src/actions/RunCommandAction.ts b/src/actions/RunCommandAction.ts
index 17c30aa..8b03b0a 100644
--- a/src/actions/RunCommandAction.ts
+++ b/src/actions/RunCommandAction.ts
@@ -22,9 +22,17 @@ export class RunCommandAction extends Action {
         return;
       }
     }
+
+    // expand any macros in the command or arguments
+    let expandedCommand = widget.expandMacro(this.command);
+    let expandedArgs : { [key: string]: string } = {};
+    for (let item in this.args) {
+      expandedArgs[item] = widget.expandMacro(this.args[item]);
+    }
+
     const event: RunCommandEvent = {
-      command: this.command,
-      args: this.args,
+      command: expandedCommand,
+      args: expandedArgs,
     };
     widget.display.fireEvent("runcommand", event);
   }

**Comment by fqqb** [comment]
Thanks, included in v1.2.11
